### ISSUE TITLE
Add specs for engine.ts

### ISSUE THREAD

**Issue by imanpalsingh** [imanpalsingh/pg-faker#132]
## Description
Specs are required for [`engine.ts`](https://github.com/imanpalsingh/pg-faker/blob/main/src/cli/engine.ts). Similar specs are present [here](https://github.com/imanpalsingh/pg-faker/tree/main/src/cli/__tests__).

**Comment by mayankshukla94** [comment]
@imanpalsingh I can pick this

**Comment by imanpalsingh** [comment]
sure @mayankshukla94
